# NUMPY

In [1]:
!pip install numpy

In [2]:
 import numpy as np

In [15]:
my_list = [1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [16]:
array = np.array(my_list,dtype=int)
print(array)

[1 2 3 4 5 6]


In [17]:
print(type(array))

<class 'numpy.ndarray'>


In [18]:
print(len(array))

6


In [19]:
print(array.ndim)

1


In [20]:
print(array.shape)

(6,)


In [21]:
array2 = array.reshape(3,2)
print(array2)

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [23]:
array3 = array.reshape(3,-1)
print(array3)

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [24]:
array3.shape

(3, 2)

In [25]:
my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,8,7,6,5]

In [26]:
mul_arr = np.array([my_list2,my_list3,my_list4])
print(mul_arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 8 7 6 5]]


In [27]:
print(mul_arr.shape)

(3, 5)


In [32]:
mul_arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 8, 7, 6, 5]])

#NUMPY ATTRIBUTE

In [34]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [39]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [41]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
r = range(24)

In [43]:
print(r)

range(0, 24)


In [45]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [46]:
print(a.ndim)

1


In [47]:
b = a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


#NUMPY ARITHMETIC OPERATION

In [48]:
x = np.array([[1,2],[3,4]],dtype = np.float64)
y = np.array([[6,7],[8,9]],dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[6. 7.]
 [8. 9.]]


#add() b/w 2 np arays

In [53]:
(x+y)
print(np.add(x,y))

[[ 7.  9.]
 [11. 13.]]


#sub()

In [51]:
print(x-y)

[[-5. -5.]
 [-5. -5.]]


In [54]:
print(x.dot(y))

[[22. 25.]
 [50. 57.]]


In [55]:
print(np.dot(x,y))

[[22. 25.]
 [50. 57.]]


In [56]:
print(x/y)

[[0.16666667 0.28571429]
 [0.375      0.44444444]]


#numpy sum()

In [57]:
print(np.sum(x))
print(x)

10.0
[[1. 2.]
 [3. 4.]]


In [58]:
print(np.sum(x,axis=0))  #compute sum of column

[4. 6.]


In [59]:
print(np.sum(x,axis=1)) #compute sum of row

[3. 7.]
